import { Component } from '@angular/core';

@Component({
  selector: 'app-loading-spinner',
  template: `<div class="loadingio-spinner-rolling-5lyyns4262e">
      <div class="ldio-uxi36aptmks">
        <div></div>
      </div>
    </div>
    <style type="text/css">
      @keyframes ldio-uxi36aptmks {
        0% {
          transform: translate(-50%, -50%) rotate(0deg);
        }
        100% {
          transform: translate(-50%, -50%) rotate(360deg);
        }
      }
      .ldio-uxi36aptmks div {
        position: absolute;
        width: 120px;
        height: 120px;
        border: 20px solid #043278;
        border-top-color: transparent;
        border-radius: 50%;
      }
      .ldio-uxi36aptmks div {
        animation: ldio-uxi36aptmks 1s linear infinite;
        top: 100px;
        left: 100px;
      }
      .loadingio-spinner-rolling-5lyyns4262e {
        width: 200px;
        height: 200px;
        display: inline-block;
        overflow: hidden;
        background: #f1f2f3;
      }
      .ldio-uxi36aptmks {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(1);
        backface-visibility: hidden;
        transform-origin: 0 0; /* see note above */
      }
      .ldio-uxi36aptmks div {
        box-sizing: content-box;
      }
      /* generated by https://loading.io/ */
    </style>`,
  styleUrls: ['./loading-spinner.component.css'],
})
export class LoadingSpinnerComponent {}
